### ISSUE TITLE
Consider support for PmaAbsoluteUri

### ISSUE THREAD

**Issue by nazar-pc** [nazar-pc/docker-phpmyadmin#10]
Question from @abuisine at Docker Hub

**Comment by nazar-pc** [comment]
Implemented in 1e5b12a

**Comment by chorsnell** [comment]
FYI, this seems to have since been disabled :(

https://github.com/phpmyadmin/docker/issues/40

Has been requested to be put back in, follow the issue here:

https://github.com/phpmyadmin/phpmyadmin/issues/12374

**Comment by nazar-pc** [comment]
I've subscribed to that issue. I'll leave option as is for now, but will remove or change according to upstream news. Thanks for the info.

**Comment by abuisine** [comment]
Should be solved in 4.6.5, and available in 4.6.4 maintenance branch

**Comment by nazar-pc** [comment]
Will update image to 4.6.5 as soon as it is released
