### ISSUE TITLE
Bad redirection after login

### ISSUE THREAD

**Issue by yomguy** [nazar-pc/docker-phpmyadmin#11]
Hi,
First, thanks for your work!
I have a bad redirection after login, for example:

http://phpmyadmin/index.php?token=7cf8cf2463be23991bae7c3f1c0e2a9c

like the domain is missed.

**Comment by nazar-pc** [comment]
Can you provide some more details about your configuration? I mean which webservers used before phpmyadmin and configs of related virtual hosts?

**Comment by yomguy** [comment]
Sure. Here is the adding in my composition:
https://github.com/Parisson/Telemeta/blob/dev/docker-compose.yml#L91

and the related nginx config:
https://github.com/Parisson/Telemeta/blob/dev/app/deploy/nginx-app.conf#L23

**Comment by yomguy** [comment]
oh, as I'm writing to you, I realize that the form is redirecting to the docker composition subdomain, not the main one which does proxying. Maybe I need some more nginx header parameters..

**Comment by nazar-pc** [comment]
Yes, try to do it like this:

```
location /phpmyadmin {
               proxy_pass http://phpmyadmin/;
               proxy_set_header Host $host;
}
```

**Comment by nazar-pc** [comment]
Also #10 seems to be related here

**Comment by yomguy** [comment]
yes, better because it gets the domain, but not the relative subpath (/phpmyadmin/) I'm afraid.

**Comment by yomguy** [comment]
then do you think it's possible to get the phpmyadmin config as a volume and assign PmaAbsoluteUri ?

**Comment by nazar-pc** [comment]
I've just pushed significant update, try this now: https://github.com/nazar-pc/docker-phpmyadmin#custom-uri-of-phpmyadmin-instance
But I didn't get why you might need a volume here (though, there should be no problems with it).

**Comment by yomguy** [comment]
Great ! pulling...

**Comment by yomguy** [comment]
OK, thanks ! Working nice giving the absolute URI in the composition.
However, I would prefer to not specify any external domain in the generic composition so that the app can start from any host (like we want for any web application). Don't you think PMA could detect its own $host and relative URI during login ? I know this is about out of the scope, but I'm surprised PMA cannot behaves well behind any relative path.

**Comment by yomguy** [comment]
My surprise is also due to the fact that _after_ login, everything is OK for PMA...

**Comment by nazar-pc** [comment]
I guess you have to look at source code and probably post an issue in phpMyAdmin repository.
Generally, specifying right headers  in Nginx vhost should make phpMyAdmin happy, but I'm not familiar with details under the hood, didn't need that yet.

**Comment by yomguy** [comment]
I understand your point of view and really appreciate your help.
BTW don't you think it could be induced by the Apache config of the container ? I've indeed already seen or use a working PMA instance behind a complex URI ;)

**Comment by nazar-pc** [comment]
I'm pretty sure this is just a matter of right config. But including any changes in this repo means that it should be general-purpose.

**Comment by yomguy** [comment]
I've just checked the last config I use which was driven by php-fpm behind nginx... nothing comparable to your setup but working:

```
   location /phpmyadmin {
        root /usr/share/;
        index index.php index.html index.htm;

        location ~ ^/phpmyadmin/(.+\.php)$ {
            try_files $uri =404;
            root /usr/share/;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include /etc/nginx/fastcgi_params;
        }

        location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
            root /usr/share/;
        }
    }

    location /phpMyAdmin {
        rewrite ^/* /phpmyadmin last;
    }
```

**Comment by yomguy** [comment]
Of course I agree with the "general-purpose"  of this repo ;)

**Comment by nazar-pc** [comment]
There are some ideas (though, not for Nginx) in wiki: https://wiki.phpmyadmin.net/pma/Config/PmaAbsoluteUri

**Comment by yomguy** [comment]
I can't have it work the generic way for the moment after trying various nginx configs (with various proxy_set_header and proxy_cookie_path values) but without success. I think there is something to do  between your apache and my nginx to get the right redirection.
But, as it works well using your later ABSOLUTE_URI option - even it offer a non generic solution - and as I can also use a separate port for PMA - which works well - I can close this issue.
I will ping you again when I find a better solution around the configs...
Thanks for helping !
Cheers,
Guillaume
