### ISSUE TITLE
#1045 - Access denied for user 'root'@'172.17.0.3' (using password: YES)

### ISSUE THREAD

**Issue by Bodge-IT** [nazar-pc/docker-phpmyadmin#12]
Hi Nazar, thanks for the work on the container.

I have tried the instructions as described but get no access.  I know the password is correct as I can exec into mysql container and verify.

Any ideas?

**Comment by nazar-pc** [comment]
Initial thought is that you probably didn't set correct alias when linking containers. Can you provide some more details how exactly you're trying to use it?

**Comment by Bodge-IT** [comment]
Hi, I'm using this MySQl container: https://github.com/sameersbn/docker-redmine with yours.

Just trying to setup Redmine but need to import database backup first

**Comment by nazar-pc** [comment]
Check MySQL configuration inside of that container and make sure it listen to connections on public interface, it might be the case that MySQL only listen on `127.0.0.1` or even local Unix socket and thus you'll not have access to it from PhpMyAdmin. Typically, changing address from `127.0.0.1` or local Unix socket to `0.0.0.0` should help.
