### ISSUE TITLE
Upgrade to PHP7

### ISSUE THREAD

**Issue by davidwindell** [nazar-pc/docker-phpmyadmin#18]
It would be great to see an upgrade to PHP7 as 5.6 is no longer supported.

**Comment by nazar-pc** [comment]
Thanks for noticing!
I've just upgraded PHP to 7.1 in 2c45c94

In my environment it works fine, let me know if you find something wrong with it.

**Comment by davidwindell** [comment]
Awesome, I'll check that out!
