### ISSUE TITLE
Increase max_execution_time

### ISSUE THREAD

**Issue by Sineos** [nazar-pc/docker-phpmyadmin#20]
I want to import a quite large file into mysql and would need to increase `max_execution_time`. Is there a way to do so?

**Comment by nazar-pc** [comment]
PhpMyAdmin usually splits upload into pieces and uploads even large files without much issues.
Did you try it?

**Comment by Sineos** [comment]
I have not found such an option. I want to import a csv file, so I created a new database, went to import, added my csv, set the options and hit go.

**Comment by nazar-pc** [comment]
On import page below `File to import:` there should be `Partial import:` section. For me it is selected by default. Also often you can make it faster by compressing file with something like bz2.
