### ISSUE TITLE
Compatibility with OpenShift container platform

### ISSUE THREAD

**Issue by bittner** [nazar-pc/docker-phpmyadmin#21]
We're using this image for our customers who want to run phpMyAdmin on [OpenShift](https://www.openshift.com/). OpenShift requires the user running inside the container not to be `root` (to avoid privileged access to the host machine).

We've made the [necessary adaptions](https://github.com/vshn/docker-phpmyadmin/blob/master/Dockerfile#L7-L12), following the proposed changes of the [OpenShift documentation](https://docs.openshift.com/container-platform/3.7/creating_images/guidelines.html#use-uid), in [our own image](https://hub.docker.com/r/vshn/phpmyadmin/).

Would you like those changes [integrated in your entrypoint](https://github.com/nazar-pc/docker-phpmyadmin/blob/master/docker-entrypoint.sh#L9)? We could introduce new environment variables, e.g.

* `HTTP_PORT=80`
* `HTTPS_PORT=443`

... and the group ownership could be `root` by default in the [Dockerfile](https://github.com/nazar-pc/docker-phpmyadmin/blob/master/Dockerfile), which probably wouldn't harm.

This way users wanting to run on OpenShift may simply set the two environment variables from above (plus `MYSQL_HOST`, probably), and all would be good. No dedicated Docker image required!

How does that sound? Would you accept such a PR?

**Comment by nazar-pc** [comment]
Yes, makes perfect sense to me, would be happy to accept such changes to avoid fragmentation

**Comment by bittner** [comment]
Thanks for merging #22 and #24! The image built on Docker Hub works fine, just verified it successfully.

BTW, you may want to add a tag "openshift" to the respository now, I thought, for discoverability.
