### ISSUE TITLE
ssh access included

### ISSUE THREAD

**Issue by ehwest** [nazar-pc/docker-phpmyadmin#26]
Its not clear if you also have ssh server services installed on this?

**Comment by nazar-pc** [comment]
No, there is no SSH as there shouldn't be

**Comment by Habib-Rehhman** [comment]
Hi nazar, can't we configure ssh service?. what do u by this reply "No, there is no SSH as there shouldn't be"

**Comment by Habib-Rehhman** [comment]
Hi nazar, how can I configure SSL with phpmyadmin?

**Comment by nazar-pc** [comment]
You use something like Nginx in front of PhpMyAdmin as you usually do with other apps.
But don't hijack unrelated tickets, please. Create a new one if you need.
