### ISSUE TITLE
How to access via https?

### ISSUE THREAD

**Issue by sawweee** [nazar-pc/docker-phpmyadmin#27]
I've set up HTTPS_PORT environment variable and also paired local port with container port. However I'm still unable to access phpMyAdmin via https, it seems https port on the container is actually not opened.
What do I do wrong?

**Comment by nazar-pc** [comment]
Did you also expose the port on a container like here?: https://github.com/nazar-pc/docker-phpmyadmin#custom-ports-for-http-and-https-inside-the-container
