### ISSUE TITLE
Can't stop the container with Ctrl+C !!!!

### ISSUE THREAD

**Issue by HatemJerbi** [nazar-pc/docker-phpmyadmin#7]

**Comment by nazar-pc** [comment]
This container has nothing special on top of default PHP container in terms of Web Server.
Namely, `apache2-foreground` command is used just like in official image: https://github.com/docker-library/php/blob/fec7f537f049aafd2102202519c3ca9cb9576707/5.6/apache/Dockerfile

Try to reproduce with container `php:apache`, if you can reproduce this as well - you should create issue about this in [Docker repository](https://github.com/docker/docker).

Anyway, you can stop container by finding its id using `docker ps` and then just `docker stop container_id`.
